export type ConnectionPoint = {
  id: string
  label: string
  x: number
  y: number
  kind: 'breadboard-hole' | 'pin' | 'rail'
  confidence?: number
  snapSource?: 'detected-hole' | 'manual' | 'grid-fill'
  /** Region this point belongs to when generated by the grid-fill tool. */
  regionId?: string
  /** Row group within `regionId` when rows are linked as a rail. */
  rowId?: string
  /** Column group within `regionId` when columns are linked as a rail. */
  columnId?: string
}

export type DefinitionRegionKind = 'terminal-strip' | 'power-rail' | 'custom-grid'

export type DefinitionAxisGroup = {
  id: string
  label: string
  pointIds: string[]
}

export type DefinitionRegion = {
  id: string
  name: string
  kind: DefinitionRegionKind
  pointIds: string[]
  /** Linked rows (each row's points are electrically connected). */
  rows: DefinitionAxisGroup[]
  /** Linked columns (each column's points are electrically connected). */
  columns: DefinitionAxisGroup[]
}

/**
 * Two-point scale calibration stored on the breadboard definition.
 * x1/y1 and x2/y2 are in image-pixel space (same coordinate system as
 * ConnectionPoint x/y).  realDistanceMm is the known real-world distance
 * between those two points in millimetres.
 */
export type ScaleCalibration = {
  x1: number
  y1: number
  x2: number
  y2: number
  realDistanceMm: number
}

export type BreadboardDefinition = {
  id: string
  name: string
  imageName: string
  imagePath: string
  imageWidth: number
  imageHeight: number
  points: ConnectionPoint[]
  scaleCalibration?: ScaleCalibration
  regions?: DefinitionRegion[]
  createdAt: string
  updatedAt: string
}

type BreadboardDefinitionDraft = Partial<Omit<BreadboardDefinition, 'points' | 'regions'>> & {
  points?: ConnectionPoint[]
  regions?: DefinitionRegion[]
}

function createDefinitionId() {
  if (typeof crypto !== 'undefined' && typeof crypto.randomUUID === 'function') {
    return crypto.randomUUID()
  }

  return `breadboard-definition-${Date.now()}`
}

function createUuidWithPrefix(prefix: string) {
  if (typeof crypto !== 'undefined' && typeof crypto.randomUUID === 'function') {
    return `${prefix}-${crypto.randomUUID()}`
  }
  return `${prefix}-${Date.now()}-${Math.round(Math.random() * 1_000_000)}`
}

export function createRegionId() {
  return createUuidWithPrefix('region')
}

export function createAxisGroupId() {
  return createUuidWithPrefix('axis-group')
}

export function cloneDefinitionRegion(region: DefinitionRegion): DefinitionRegion {
  return {
    ...region,
    pointIds: [...region.pointIds],
    rows: region.rows.map((g) => ({ ...g, pointIds: [...g.pointIds] })),
    columns: region.columns.map((g) => ({ ...g, pointIds: [...g.pointIds] })),
  }
}

export function cloneConnectionPoint(point: ConnectionPoint): ConnectionPoint {
  return {
    ...point,
  }
}

export function cloneBreadboardDefinition(definition: BreadboardDefinition): BreadboardDefinition {
  return {
    ...definition,
    points: definition.points.map(cloneConnectionPoint),
    scaleCalibration: definition.scaleCalibration ? { ...definition.scaleCalibration } : undefined,
    regions: definition.regions ? definition.regions.map(cloneDefinitionRegion) : undefined,
  }
}

export function createEmptyBreadboardDefinition(
  definition: BreadboardDefinitionDraft = {},
): BreadboardDefinition {
  const timestamp = definition.createdAt ?? definition.updatedAt ?? new Date().toISOString()

  return {
    id: definition.id ?? createDefinitionId(),
    name: definition.name ?? 'Untitled breadboard definition',
    imageName: definition.imageName ?? '',
    imagePath: definition.imagePath ?? '',
    imageWidth: definition.imageWidth ?? 0,
    imageHeight: definition.imageHeight ?? 0,
    points: definition.points?.map(cloneConnectionPoint) ?? [],
    scaleCalibration: definition.scaleCalibration ? { ...definition.scaleCalibration } : undefined,
    regions: definition.regions ? definition.regions.map(cloneDefinitionRegion) : undefined,
    createdAt: definition.createdAt ?? timestamp,
    updatedAt: definition.updatedAt ?? timestamp,
  }
}